import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { Infer, v } from "convex/values";

// ─── Enums / Role Validators ─────────────────────────────────────────────────

export const ROLES = {
  ADMIN: "admin",
  USER: "user",
  MEMBER: "member",
} as const;

export const roleValidator = v.union(
  v.literal(ROLES.ADMIN),
  v.literal(ROLES.USER),
  v.literal(ROLES.MEMBER),
);
export type Role = Infer<typeof roleValidator>;

export const AGENT_STATUS = {
  IDLE: "idle",
  WORKING: "working",
  REVIEWING: "reviewing",
  BLOCKED: "blocked",
  ERROR: "error",
  RETIRED: "retired",
} as const;

export const agentStatusValidator = v.union(
  v.literal(AGENT_STATUS.IDLE),
  v.literal(AGENT_STATUS.WORKING),
  v.literal(AGENT_STATUS.REVIEWING),
  v.literal(AGENT_STATUS.BLOCKED),
  v.literal(AGENT_STATUS.ERROR),
  v.literal(AGENT_STATUS.RETIRED),
);
export type AgentStatus = Infer<typeof agentStatusValidator>;

export const AGENT_TYPE = {
  BOSS: "boss",
  WORKER: "worker",
  REVIEWER: "reviewer",
  SPECIALIST: "specialist",
} as const;

export const agentTypeValidator = v.union(
  v.literal(AGENT_TYPE.BOSS),
  v.literal(AGENT_TYPE.WORKER),
  v.literal(AGENT_TYPE.REVIEWER),
  v.literal(AGENT_TYPE.SPECIALIST),
);
export type AgentType = Infer<typeof agentTypeValidator>;

export const TASK_STATUS = {
  PENDING: "pending",
  IN_PROGRESS: "in_progress",
  IN_REVIEW: "in_review",
  COMPLETED: "completed",
  FAILED: "failed",
  BLOCKED: "blocked",
  CANCELLED: "cancelled",
} as const;

export const taskStatusValidator = v.union(
  v.literal(TASK_STATUS.PENDING),
  v.literal(TASK_STATUS.IN_PROGRESS),
  v.literal(TASK_STATUS.IN_REVIEW),
  v.literal(TASK_STATUS.COMPLETED),
  v.literal(TASK_STATUS.FAILED),
  v.literal(TASK_STATUS.BLOCKED),
  v.literal(TASK_STATUS.CANCELLED),
);
export type TaskStatus = Infer<typeof taskStatusValidator>;

export const CHANNEL_TYPE = {
  GROUP: "group",
  DIRECT: "direct",
  THREAD: "thread",
} as const;

export const channelTypeValidator = v.union(
  v.literal(CHANNEL_TYPE.GROUP),
  v.literal(CHANNEL_TYPE.DIRECT),
  v.literal(CHANNEL_TYPE.THREAD),
);
export type ChannelType = Infer<typeof channelTypeValidator>;

export const TOOL_CATEGORY = {
  BROWSER: "browser",
  CODE: "code",
  FILE: "file",
  GITHUB: "github",
  EMAIL: "email",
  DATABASE: "database",
  API: "api",
  MCP: "mcp",
  A2A: "a2a",
  CUSTOM: "custom",
} as const;

export const toolCategoryValidator = v.union(
  v.literal(TOOL_CATEGORY.BROWSER),
  v.literal(TOOL_CATEGORY.CODE),
  v.literal(TOOL_CATEGORY.FILE),
  v.literal(TOOL_CATEGORY.GITHUB),
  v.literal(TOOL_CATEGORY.EMAIL),
  v.literal(TOOL_CATEGORY.DATABASE),
  v.literal(TOOL_CATEGORY.API),
  v.literal(TOOL_CATEGORY.MCP),
  v.literal(TOOL_CATEGORY.A2A),
  v.literal(TOOL_CATEGORY.CUSTOM),
);
export type ToolCategory = Infer<typeof toolCategoryValidator>;

// ─── Schema ──────────────────────────────────────────────────────────────────

const schema = defineSchema(
  {
    // Auth tables (auto-generated by Convex Auth — do not remove)
    ...authTables,

    // ── Users ──────────────────────────────────────────────────────────────
    users: defineTable({
      name: v.optional(v.string()),
      image: v.optional(v.string()),
      email: v.optional(v.string()),
      emailVerificationTime: v.optional(v.number()),
      isAnonymous: v.optional(v.boolean()),
      role: v.optional(roleValidator),
    }).index("email", ["email"]),

    // ── Projects ───────────────────────────────────────────────────────────
    projects: defineTable({
      name: v.string(),
      description: v.optional(v.string()),
      goal: v.optional(v.string()),
      ownerId: v.id("users"),
      status: v.union(v.literal("active"), v.literal("archived"), v.literal("completed")),
      tags: v.optional(v.array(v.string())),
    })
      .index("owner", ["ownerId"])
      .index("status", ["status"]),

    // ── Project Members ────────────────────────────────────────────────────
    projectMembers: defineTable({
      projectId: v.id("projects"),
      userId: v.id("users"),
      role: roleValidator,
      joinedAt: v.number(),
    })
      .index("project", ["projectId"])
      .index("user", ["userId"])
      .index("project_user", ["projectId", "userId"]),

    // ── Agents ─────────────────────────────────────────────────────────────
    agents: defineTable({
      projectId: v.id("projects"),
      name: v.string(),
      type: agentTypeValidator,
      status: agentStatusValidator,
      emoji: v.optional(v.string()),
      description: v.optional(v.string()),
      systemPrompt: v.optional(v.string()),
      capabilities: v.optional(v.array(v.string())),
      parentAgentId: v.optional(v.id("agents")),
      llmModel: v.optional(v.string()),
      temperature: v.optional(v.number()),
      maxTokens: v.optional(v.number()),
      color: v.optional(v.string()),
      createdAt: v.number(),
      retiredAt: v.optional(v.number()),
    })
      .index("project", ["projectId"])
      .index("parent", ["parentAgentId"])
      .index("status", ["status"])
      .index("type", ["type"]),

    // ── Tasks ──────────────────────────────────────────────────────────────
    tasks: defineTable({
      projectId: v.id("projects"),
      title: v.string(),
      description: v.optional(v.string()),
      status: taskStatusValidator,
      priority: v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("critical")),
      assignedAgentId: v.optional(v.id("agents")),
      assignedUserId: v.optional(v.id("users")),
      parentTaskId: v.optional(v.id("tasks")),
      dependencies: v.optional(v.array(v.id("tasks"))),
      createdBy: v.id("users"),
      createdAt: v.number(),
      startedAt: v.optional(v.number()),
      completedAt: v.optional(v.number()),
      deadline: v.optional(v.number()),
      tags: v.optional(v.array(v.string())),
      result: v.optional(v.string()),
      metadata: v.optional(v.any()),
    })
      .index("project", ["projectId"])
      .index("status", ["status"])
      .index("agent", ["assignedAgentId"])
      .index("parent", ["parentTaskId"])
      .index("assignee", ["assignedUserId"]),

    // ── Channels (group chats, direct messages, threads) ───────────────────
    channels: defineTable({
      projectId: v.id("projects"),
      name: v.string(),
      type: channelTypeValidator,
      agentIds: v.array(v.id("agents")),
      participantUserIds: v.optional(v.array(v.id("users"))),
      parentChannelId: v.optional(v.id("channels")),
      isDefault: v.optional(v.boolean()),
      createdAt: v.number(),
      lastActivityAt: v.number(),
    })
      .index("project", ["projectId"])
      .index("type", ["type"])
      .index("parent", ["parentChannelId"]),

    // ── Messages ───────────────────────────────────────────────────────────
    messages: defineTable({
      channelId: v.id("channels"),
      projectId: v.id("projects"),
      senderId: v.id("users"),
      senderName: v.string(),
      senderType: v.union(v.literal("user"), v.literal("agent")),
      agentId: v.optional(v.id("agents")),
      content: v.string(),
      contentType: v.union(v.literal("text"), v.literal("code"), v.literal("image"), v.literal("file"), v.literal("system")),
      mentions: v.optional(v.array(v.id("agents"))),
      parentMessageId: v.optional(v.id("messages")),
      threadChannelId: v.optional(v.id("channels")),
      metadata: v.optional(v.any()),
      createdAt: v.number(),
      editedAt: v.optional(v.number()),
    })
      .index("channel", ["channelId"])
      .index("project", ["projectId"])
      .index("sender", ["senderId"])
      .index("agent", ["agentId"])
      .index("parent", ["parentMessageId"])
      .index("channel_time", ["channelId", "createdAt"]),

    // ── Tool Definitions ───────────────────────────────────────────────────
    tools: defineTable({
      projectId: v.id("projects"),
      name: v.string(),
      description: v.string(),
      category: toolCategoryValidator,
      config: v.any(),
      enabled: v.boolean(),
      allowedAgentIds: v.optional(v.array(v.id("agents"))),
      requiresApproval: v.boolean(),
      createdAt: v.number(),
    })
      .index("project", ["projectId"])
      .index("category", ["category"])
      .index("enabled", ["enabled"]),

    // ── Approval Gates ─────────────────────────────────────────────────────
    approvals: defineTable({
      projectId: v.id("projects"),
      agentId: v.id("agents"),
      taskId: v.optional(v.id("tasks")),
      action: v.string(),
      description: v.string(),
      status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")),
      requestedBy: v.id("users"),
      approvedBy: v.optional(v.id("users")),
      requestedAt: v.number(),
      resolvedAt: v.optional(v.number()),
      metadata: v.optional(v.any()),
    })
      .index("project", ["projectId"])
      .index("agent", ["agentId"])
      .index("task", ["taskId"])
      .index("status", ["status"]),

    // ── Memories / Knowledge ───────────────────────────────────────────────
    memories: defineTable({
      projectId: v.id("projects"),
      agentId: v.optional(v.id("agents")),
      type: v.union(v.literal("conversation"), v.literal("decision"), v.literal("fact"), v.literal("code"), v.literal("document")),
      title: v.string(),
      content: v.string(),
      embedding: v.optional(v.array(v.float64())),
      sourceIds: v.optional(v.array(v.string())),
      tags: v.optional(v.array(v.string())),
      createdAt: v.number(),
    })
      .index("project", ["projectId"])
      .index("agent", ["agentId"])
      .index("type", ["type"]),

    // ── Knowledge Graph Edges ──────────────────────────────────────────────
    knowledgeEdges: defineTable({
      sourceMemoryId: v.id("memories"),
      targetMemoryId: v.id("memories"),
      relationship: v.string(),
      weight: v.optional(v.number()),
      createdAt: v.number(),
    })
      .index("source", ["sourceMemoryId"])
      .index("target", ["targetMemoryId"]),

    // ── Execution Logs (Observability) ─────────────────────────────────────
    executionLogs: defineTable({
      projectId: v.id("projects"),
      agentId: v.id("agents"),
      taskId: v.optional(v.id("tasks")),
      action: v.string(),
      status: v.union(v.literal("started"), v.literal("completed"), v.literal("failed")),
      input: v.optional(v.any()),
      output: v.optional(v.any()),
      tokensUsed: v.optional(v.number()),
      costUsd: v.optional(v.number()),
      latencyMs: v.optional(v.number()),
      model: v.optional(v.string()),
      error: v.optional(v.string()),
      createdAt: v.number(),
      completedAt: v.optional(v.number()),
    })
      .index("project", ["projectId"])
      .index("agent", ["agentId"])
      .index("task", ["taskId"])
      .index("status", ["status"])
      .index("created", ["createdAt"]),

    // ── Workspace Files ────────────────────────────────────────────────────
    workspaces: defineTable({
      projectId: v.id("projects"),
      agentId: v.optional(v.id("agents")),
      name: v.string(),
      type: v.union(v.literal("directory"), v.literal("file")),
      parentId: v.optional(v.id("workspaces")),
      content: v.optional(v.string()),
      mimeType: v.optional(v.string()),
      size: v.optional(v.number()),
      metadata: v.optional(v.any()),
      createdAt: v.number(),
      updatedAt: v.number(),
    })
      .index("project", ["projectId"])
      .index("agent", ["agentId"])
      .index("parent", ["parentId"]),

    // ── Notifications ──────────────────────────────────────────────────────
    notifications: defineTable({
      userId: v.id("users"),
      projectId: v.optional(v.id("projects")),
      type: v.union(v.literal("mention"), v.literal("task"), v.literal("approval"), v.literal("message"), v.literal("system")),
      title: v.string(),
      body: v.string(),
      read: v.boolean(),
      link: v.optional(v.string()),
      createdAt: v.number(),
    })
      .index("user", ["userId"])
      .index("read", ["userId", "read"])
      .index("user_time", ["userId", "createdAt"]),
  },
  {
    schemaValidation: false,
  },
);

export default schema;
